spring:
    application:
        name: center-monitor

server:
    port: 8764 #启动端口

eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

management:
  security:
      enabled: false
